[package]
name = "hyper-ws"
version = "0.1.0"
authors = ["Matt Hunzinger <matthunz2@gmail.com>"]
edition = "2018"

[lib]
name = "hyper_ws"

[dependencies]
hyper = "0.13.5"
tokio = "0.2.21"
tower-service = "0.3.0"
ws-async = { git = "https://github.com/matthunz/ws-async" }
