[package]
name = "hyper-ws"
version = "0.1.0"
authors = ["Matt Hunzinger <matthunz2@gmail.com>"]
edition = "2018"

[lib]
name = "hyper_ws"

[dependencies]
ws-async = { git = "https://github.com/matthunz/ws-async" }
